# Generated by Django 2.2.16 on 2020-11-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20201111_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
